/** Aircraft roster — research-backed physics, procedures & control sets (SI units) */
import { HANDLING } from './craft-details.js';

/** Speeds m/s, mass kg, thrust N, rates rad/s. See docs/aircraft-research.md & physics-targets.md */

export const AIRCRAFT = [
  {
    id: 'cessna182',
    name: 'Cessna 182',
    blurb: 'Forgiving Skylane — mixture/prop/flaps procedure',
    fictional: false,
    diff: 'easy',
    type: 'prop',
    color: 0xfff6ee,
    accent: 0x1e6ad8,
    mass: 1350,
    wingArea: 16.2,
    maxThrust: 2900,
    idleThrust: 80,
    drag: 0.034,
    liftCoef: 1.4,
    stallSpeed: 28,
    stallSpeedFlaps: 24,
    cruiseSpeed: 75,
    maxSpeed: 90,
    vno: 72,
    vr: 28,
    vref: 34,
    v2: 36,
    climbRate: 4.7,
    rollRate: 1.2,
    pitchRate: 0.9,
    yawRate: 0.6,
    flapLift: 0.35,
    flapDrag: 0.08,
    gearDrag: 0.018,
    flapSteps: [0, 0.33, 0.66, 1],
    flapLabels: ['0°', '10°', '20°', '30°'],
    flapTakeoff: 0,
    flapTakeoffAlt: 0.66,
    flapLanding: 1,
    flapApproach: 0.66,
    landSpeedMax: 38,
    landVertMax: 3.8,
    stallAoA: 15 * Math.PI / 180,
    stallAoAFlaps: 13 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: true,
    gearRetractable: false,
    canWater: false,
    ejectOk: true,
    size: 1.0,
    controls: ['THR', 'FLAPS', 'MIX', 'PROP', 'BRAKE', 'TRIM'],
    flareStartAgl: 6.5,
    flareHoldOffFloor: 0.35,
    flareIdleThr: 0.18,
    flarePitchMin: -0.05,
    stableGateAgl: 152,
    approachSpeedMin: 30,
    approachSpeedMax: 42,
    tdzPreferMax: 650,
    requireSpoilersArmed: false,
    flareAssistDefault: true,
    parkCapable: true,
        windSense: 1.35,
    dutchRoll: 1.0,
    weathervane: 1.75,
    groundRollDrag: 0.018,
    takeoffAccelScale: 1.15,
    controlInertia: 0.15,
    gePeak: 0.22,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    nosewheelAuth: 1.35,
    engineSpool: 0.28,
    inputExpo: 1.22,
    tiltGain: 1.08,
    controlLag: 0.05,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'BRAKE', 'TRIM'] },
        { id: 'SYS', controls: ['MIX', 'PROP'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      BRAKE: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasMixture: true,
    hasProp: true,
    hasSpoilers: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: false,
    enforceFlapsLanding: false,
    enforceGear: false,
    enforceStableApproach: false,
    takeoffChecklist: [
      { id: 'mix', label: 'Mixture RICH', check: (s) => s.mixtureRich },
      { id: 'prop', label: 'Prop FULL FWD', check: (s) => s.propFull },
      { id: 'flaps', label: 'Flaps 0° (or 20° short)', check: (s) => s.flaps <= 0.7 },
      { id: 'thr', label: 'Throttle FULL', check: (s) => s.throttle >= 0.9 },
      { id: 'vr', label: 'Rotate ~55 kt (28 m/s)', check: (s) => s.speed >= 26 && s.rotating },
      { id: 'climb', label: 'Climb Vy ~80 kt', check: (s) => s.airborne && s.speed >= 35 }
    ],
    landingChecklist: [
      { id: 'config', label: 'MIX RICH · PROP FULL · flaps 30°', check: (s) => s.mixtureRich && s.propFull && s.flaps >= 0.9 },
      { id: 'stable', label: 'Stable / VRef 65–70 kt', check: (s) => s.speed >= 30 && s.speed <= 40 && (s.stableApproach !== false) },
      { id: 'align', label: 'Aligned with runway', check: (s) => s.onRunwayApproach || s.headingAligned },
      { id: 'flare', label: 'Flare window — idle', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.15 && s.agl < 8) },
      { id: 'hold', label: 'Hold-off / round out', check: (s) => s.flareHoldOffOk || (s.throttle <= 0.15 && s.agl < 6 && s.pitch < -0.02) }
    ],
    howToFly: 'Gentle GA trainer feel. Use mixture RICH and prop FULL for takeoff/landing. Cycle flaps in steps. Fixed gear — no gear button.',
    howToTakeoff: 'MIX RICH, PROP FULL, flaps 0° (20° short-field). Full throttle, rotate ~55 KIAS, climb ~80 KIAS, flaps up by 70–80 kt.',
    howToLand: 'MIX/PROP full. Flaps 10→20→30 on final. Aim 65–70 kt over threshold. Idle in flare, brakes after touchdown.',
    specs: { empty: '870–905 kg', mtow: '1,406 kg', cruise: '145 KTAS', vne: '175 KIAS', climb: '924 fpm', power: '~230 hp' }
  },
  {
    id: 'privatejet',
    name: 'Citation Mustang',
    blurb: 'VLJ — flaps 15/30, gear, spoilers, hot approach',
    fictional: false,
    diff: 'med',
    type: 'jet',
    color: 0xd0d8e8,
    accent: 0x333344,
    mass: 3800,
    wingArea: 21,
    maxThrust: 13000,
    idleThrust: 400,
    drag: 0.022,
    liftCoef: 1.1,
    stallSpeed: 48,
    stallSpeedFlaps: 38,
    cruiseSpeed: 175,
    maxSpeed: 210,
    vno: 129,
    vr: 50,
    vref: 52,
    v2: 55,
    climbRate: 15.3,
    rollRate: 1.5,
    pitchRate: 1.0,
    yawRate: 0.5,
    flapLift: 0.42,
    flapDrag: 0.1,
    gearDrag: 0.03,
    spoilerDrag: 0.08,
    spoilerLiftKill: 0.35,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['UP', '15°', '30°'],
    flapTakeoff: 0.5,
    flapLanding: 1,
    flapApproach: 0.5,
    landSpeedMax: 70,
    landVertMax: 2.8,
    stallAoA: 14 * Math.PI / 180,
    stallAoAFlaps: 12 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    ejectOk: true,
    size: 1.4,
    controls: ['THR', 'FLAPS', 'GEAR', 'SPOILERS', 'REV', 'BRAKE', 'TRIM', 'ARM', 'TOGA'],
    flareStartAgl: 7.5,
    flareHoldOffFloor: 0.6,
    flareIdleThr: 0.20,
    flarePitchMin: -0.05,
    stableGateAgl: 152,
    approachSpeedMin: 48,
    approachSpeedMax: 55,
    tdzPreferMax: 450,
    requireSpoilersArmed: true,
    flareAssistDefault: true,
    autobrakeCapable: true,
    parkCapable: true,
        windSense: 0.7,
    dutchRoll: 0.28,
    weathervane: 0.65,
    groundRollDrag: 0.030,
    takeoffAccelScale: 0.82,
    controlInertia: 0.48,
    engineSpool: 2.4,
    inputExpo: 1.55,
    tiltGain: 0.9,
    controlLag: 0.18,
    gePeak: 0.11,
    earlyLiftBlock: true,
    requireFlapsToRotate: true,
    firmFlare: true,
    nosewheelAuth: 0.55,
    requireGearSpoilersGate: true,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'GEAR', 'BRAKE', 'SPOILERS'] },
        { id: 'SYS', controls: ['REV', 'ARM', 'TOGA', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      SPOILERS: { mode: 'toggle', armable: true },
      ARM: { mode: 'toggle' },
      TOGA: { mode: 'momentary', action: 'toga' },
      REV: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasSpoilers: true,
    hasMixture: false,
    hasProp: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: true,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: true,
    takeoffChecklist: [
      { id: 'flaps', label: 'Flaps 15°', check: (s) => s.flaps >= 0.4 && s.flaps <= 0.6 },
      { id: 'spdbrk', label: 'Spoilers stowed', check: (s) => !s.spoilers },
      { id: 'thr', label: 'TO thrust', check: (s) => s.throttle >= 0.85 },
      { id: 'vr', label: 'Rotate VR ~97 kt', check: (s) => s.speed >= 48 && s.rotating },
      { id: 'gear', label: 'Gear UP after climb', check: (s) => s.airborne && !s.gearDown },
      { id: 'flapsup', label: 'Flaps UP on schedule', check: (s) => s.airborne && s.speed > 70 && s.flaps < 0.2 }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear DOWN · flaps 30°', check: (s) => s.gearDown && s.flaps >= 0.9 },
      { id: 'arm', label: 'Spoilers ARMED', check: (s) => s.spoilersArmed || s.spoilers },
      { id: 'stable', label: 'Stable VRef ~100 kt', check: (s) => s.speed >= 48 && s.speed <= 58 },
      { id: 'align', label: 'Runway lined up', check: (s) => s.onRunwayApproach && s.agl < 120 },
      { id: 'flare', label: 'Flare — idle', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.2 && s.agl < 12) }
    ],
    howToFly: 'Light jet. Retract gear after takeoff. Spoilers for descent. Gear-down mandatory before landing.',
    howToTakeoff: 'Flaps 15°, spoilers IN, TO thrust → VR ~97 kt → gear UP → flaps UP after accel.',
    howToLand: 'Flaps 15, gear DOWN, flaps 30, hold VRef ~100 kt. Idle in flare; spoilers/brakes/reverse.',
    specs: { empty: '~2,430 kg', mtow: '3,921 kg', cruise: '340 KTAS', vmo: '250 KIAS', climb: '3,010 fpm', thrust: '2×1,460 lbf' }
  },
  {
    id: 'airliner',
    name: 'Narrowbody Airliner',
    blurb: 'A320/737 class — slow engines, tiny roll, brutal landing',
    fictional: false,
    diff: 'hard',
    type: 'jet',
    color: 0xf0f4f8,
    accent: 0xcc2233,
    mass: 68000,
    wingArea: 122,
    maxThrust: 220000,
    idleThrust: 8000,
    drag: 0.024,
    liftCoef: 1.05,
    stallSpeed: 82,
    stallSpeedFlaps: 57,
    cruiseSpeed: 235,
    maxSpeed: 250,
    vno: 180,
    vr: 72,
    vref: 74,
    v2: 80,
    climbRate: 13,
    rollRate: 0.32,
    pitchRate: 0.24,
    yawRate: 0.18,
    flapLift: 0.55,
    flapDrag: 0.14,
    gearDrag: 0.04,
    spoilerDrag: 0.12,
    spoilerLiftKill: 0.5,
    reverseThrustFrac: 0.45,
    flapSteps: [0, 0.25, 0.5, 0.75, 1],
    flapLabels: ['0', '1+F', '2', '3', 'FULL'],
    flapTakeoff: 0.25,
    flapLanding: 1,
    flapApproach: 0.75,
    landSpeedMax: 80,
    landVertMax: 1.35,
    stallAoA: 14 * Math.PI / 180,
    stallAoAFlaps: 12 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    ejectOk: false,
    size: 3.2,
    controls: ['THR', 'FLAPS', 'GEAR', 'SPOILERS', 'REV', 'BRAKE', 'TRIM', 'ARM', 'TOGA'],
    flareStartAgl: 10.5,
    flareHoldOffFloor: 0.7,
    flareIdleThr: 0.25,
    flarePitchMin: -0.04,
    stableGateAgl: 300,
    approachSpeedMin: 70,
    approachSpeedMax: 80,
    tdzPreferMax: 400,
    requireSpoilersArmed: true,
    landHardGate: true,
    flareAssistDefault: false,
    autobrakeCapable: true,
    parkCapable: true,
        windSense: 0.35,
    dutchRoll: 0.1,
    weathervane: 0.3,
    groundRollDrag: 0.045,
    takeoffAccelScale: 0.38,
    controlInertia: 0.93,
    gePeak: 0.06,
    earlyLiftBlock: true,
    requireFlapsToRotate: true,
    nosewheelAuth: 0.22,
    tillerHeavy: true,
    engineSpool: 5.8,
    inputExpo: 1.9,
    tiltGain: 0.68,
    controlLag: 0.48,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'GEAR', 'BRAKE', 'SPOILERS'] },
        { id: 'SYS', controls: ['REV', 'ARM', 'TOGA', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      SPOILERS: { mode: 'toggle', armable: true },
      ARM: { mode: 'toggle' },
      TOGA: { mode: 'momentary', action: 'toga' },
      REV: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasSpoilers: true,
    hasReverse: true,
    hasMixture: false,
    hasProp: false,
    hasAfterburner: false,
    hasThrustVector: false,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: true,
    stableApproachAgl: 300,
    takeoffChecklist: [
      { id: 'flaps', label: 'Flaps TO (1+F / 5)', check: (s) => s.flaps >= 0.2 && s.flaps <= 0.55 },
      { id: 'spdbrk', label: 'Spoilers stowed', check: (s) => !s.spoilers },
      { id: 'thr', label: 'TOGA / Flex thrust', check: (s) => s.throttle >= 0.9 },
      { id: 'vr', label: 'Rotate VR ~140 kt', check: (s) => s.speed >= 68 && s.rotating },
      { id: 'gear', label: 'Gear UP', check: (s) => s.airborne && !s.gearDown },
      { id: 'flapsup', label: 'Flaps UP on schedule', check: (s) => s.airborne && s.speed > 100 && s.flaps < 0.2 }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear DOWN · flaps FULL', check: (s) => s.gearDown && s.flaps >= 0.95 },
      { id: 'arm', label: 'Spoilers ARMED', check: (s) => !!s.spoilersArmed },
      { id: 'stable', label: 'Stable by ~1000 ft', check: (s) => s.speed >= 68 && s.speed <= 82 && (s.stableApproach !== false) },
      { id: 'align', label: 'Aligned / centerline', check: (s) => s.onRunwayApproach },
      { id: 'flare', label: 'Flare window — idle', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.25 && s.agl < 15) }
    ],
    howToFly: 'Heavy, slow engines, tiny roll rate. Configure or it will not fly — and will not land. Gear-up / flaps-not-full / unarmed spoilers / unstable = crash. landVertMax 1.35 m/s.',
    howToTakeoff: 'Flaps 1+F, TOGA, rotate ~140 kt, gear up, accelerate, flaps up on schedule.',
    howToLand: 'Gear down, flaps 3 then FULL, spoilers armed, stabilize ~140–145 kt by 1000 ft AGL. Firm but not hard touchdown; reverse + brakes.',
    specs: { empty: '~42 t', mtow: '~73–79 t', cruise: 'M0.78', vmo: '350 KIAS', climb: '~2,500 fpm', thrust: '2× CFM56 class' }
  },
  {
    id: 'f15',
    name: 'F-15 Fighter',
    blurb: 'AB thrust, fighter roll, AoA approach',
    fictional: false,
    diff: 'hard',
    type: 'fighter',
    color: 0x8899aa,
    accent: 0x445566,
    mass: 18000,
    wingArea: 56.5,
    maxThrust: 100000,
    abThrust: 230000,
    idleThrust: 2000,
    drag: 0.018,
    liftCoef: 1.05,
    stallSpeed: 68,
    stallSpeedFlaps: 58,
    cruiseSpeed: 280,
    maxSpeed: 450,
    vno: 420,
    vr: 60,
    vref: 78,
    v2: 70,
    climbRate: 250,
    rollRate: 4.0,
    pitchRate: 2.2,
    yawRate: 1.0,
    flapLift: 0.25,
    flapDrag: 0.06,
    gearDrag: 0.035,
    spoilerDrag: 0.06,
    spoilerLiftKill: 0.2,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['UP', 'TO', 'LDG'],
    flapTakeoff: 0.5,
    flapLanding: 1,
    flapApproach: 1,
    landSpeedMax: 95,
    landVertMax: 2.2,
    stallAoA: 22 * Math.PI / 180,
    stallAoAFlaps: 18 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    ejectOk: true,
    size: 1.6,
    controls: ['THR', 'FLAPS', 'GEAR', 'SPOILERS', 'AB', 'BRAKE', 'TRIM'],
    flareStartAgl: 6.0,
    flareHoldOffFloor: 0.5,
    flareIdleThr: 0.25,
    flarePitchMin: -0.05,
    stableGateAgl: 152,
    approachSpeedMin: 70,
    approachSpeedMax: 90,
    tdzPreferMax: 500,
    requireSpoilersArmed: false,
    flareAssistDefault: false,
    parkCapable: true,
        windSense: 0.5,
    dutchRoll: 0.15,
    weathervane: 0.4,
    groundRollDrag: 0.022,
    takeoffAccelScale: 1.4,
    controlInertia: 0.2,
    engineSpool: 1.05,
    inputExpo: 1.12,
    tiltGain: 1.22,
    controlLag: 0.04,
    gePeak: 0.06,
    earlyLiftBlock: true,
    requireFlapsToRotate: false,
    punishSlowFloat: true,
    onSpeedLanding: true,
    abThrMin: 0.6,
    nosewheelAuth: 0.7,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'GEAR', 'BRAKE', 'AB'] },
        { id: 'SYS', controls: ['SPOILERS', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      AB: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasSpoilers: true,
    hasAfterburner: true,
    hasMixture: false,
    hasProp: false,
    hasThrustVector: false,
    hasReverse: false,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: true,
    takeoffChecklist: [
      { id: 'flaps', label: 'Flaps/slats TO', check: (s) => s.flaps >= 0.4 },
      { id: 'thr', label: 'MIL or AB', check: (s) => s.throttle >= 0.8 },
      { id: 'vr', label: 'Rotate 110–130 kt', check: (s) => s.speed >= 55 && s.rotating },
      { id: 'gear', label: 'Gear UP ASAP', check: (s) => s.airborne && !s.gearDown },
      { id: 'flapsup', label: 'Flaps/slats UP', check: (s) => s.airborne && s.speed > 90 && s.flaps < 0.2 }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear DOWN · flaps LAND', check: (s) => s.gearDown && s.flaps >= 0.9 },
      { id: 'onspeed', label: 'On-speed ~140–170 kt', check: (s) => s.speed >= 70 && s.speed <= 90 },
      { id: 'align', label: 'Runway aligned', check: (s) => s.onRunwayApproach },
      { id: 'flare', label: 'Idle in flare', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.25 && s.agl < 10) }
    ],
    howToFly: 'Very high roll rate. Toggle AB for afterburner thrust band. Hot landing — manage energy.',
    howToTakeoff: 'Flaps TO, MIL→AB, rotate ~115 kt, gear up immediately, flaps up.',
    howToLand: 'Gear down, flaps land, on-speed ~150 kt. Idle flare, aerobrake then wheel brakes.',
    specs: { empty: '~13 t', mtow: 'up to 30.8 t', max: 'Mach 2.5+', climb: '~50,000 fpm', tw: '>1:1 AB', g: '+9/−3' }
  },
  {
    id: 'area51',
    name: 'Area 51 Tech',
    blurb: 'FICTIONAL thrust-vectored black project',
    fictional: true,
    diff: 'expert',
    type: 'experimental',
    color: 0x222228,
    accent: 0x44ff88,
    mass: 9500,
    wingArea: 40,
    maxThrust: 120000,
    abThrust: 180000,
    idleThrust: 500,
    drag: 0.016,
    liftCoef: 0.95,
    stallSpeed: 45,
    stallSpeedFlaps: 35,
    stallSpeedTV: 15,
    cruiseSpeed: 350,
    maxSpeed: 480,
    vno: 500,
    vr: 40,
    vref: 38,
    v2: 50,
    climbRate: 300,
    rollRate: 3.5,
    pitchRate: 2.8,
    yawRate: 2.2,
    flapLift: 0.2,
    flapDrag: 0.04,
    gearDrag: 0.02,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['UP', '½', 'FULL'],
    flapTakeoff: 0,
    flapLanding: 0.5,
    flapApproach: 0.5,
    landSpeedMax: 45,
    landVertMax: 2.0,
    stallAoA: 30 * Math.PI / 180,
    stallAoAFlaps: 28 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    thrustVector: true,
    hoverAssist: 0.88,
    ejectOk: true,
    size: 1.5,
    controls: ['THR', 'GEAR', 'FLAPS', 'TV', 'AB', 'BRAKE', 'TRIM'],
    flareStartAgl: 9.0,
    flareHoldOffFloor: 0.5,
    flareIdleThr: 0.35,
    flarePitchMin: -0.02,
    stableGateAgl: 152,
    approachSpeedMin: 30,
    approachSpeedMax: 45,
    tdzPreferMax: 500,
    requireSpoilersArmed: false,
    flareAssistDefault: false,
    parkCapable: true,
        windSense: 0.4,
    dutchRoll: 0.2,
    weathervane: 0.45,
    groundRollDrag: 0.025,
    takeoffAccelScale: 1.2,
    controlInertia: 0.25,
    engineSpool: 0.35,
    inputExpo: 1.18,
    tiltGain: 1.16,
    controlLag: 0.06,
    gePeak: 0.08,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    tvFailModes: true,
    abThrMin: 0.6,
    nosewheelAuth: 0.65,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['GEAR', 'TV', 'AB', 'BRAKE'] },
        { id: 'SYS', controls: ['FLAPS', 'TRIM'] }
      ]
    },
    controlMeta: {
      TV: { mode: 'toggle' },
      AB: { mode: 'toggle' },
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasSpoilers: false,
    hasAfterburner: true,
    hasThrustVector: true,
    hasMixture: false,
    hasProp: false,
    hasReverse: false,
    enforceFlapsLanding: false,
    enforceGear: true,
    enforceStableApproach: true,
    takeoffChecklist: [
      { id: 'tv', label: 'Thrust vector ENABLE', check: (s) => s.thrustVectorOn },
      { id: 'gear', label: 'Gear DOWN confirmed', check: (s) => s.gearDown },
      { id: 'thr', label: 'Throttle ≥70%', check: (s) => s.throttle >= 0.7 },
      { id: 'lift', label: 'Lift at 80 kt or TV vertical', check: (s) => s.rotating || (s.thrustVectorOn && s.throttle > 0.7) },
      { id: 'gearup', label: 'Gear UP', check: (s) => s.airborne && !s.gearDown }
    ],
    landingChecklist: [
      { id: 'tv', label: 'TV ON (or conventional speed)', check: (s) => s.thrustVectorOn || s.speed > 55 },
      { id: 'config', label: 'Gear DOWN', check: (s) => s.gearDown },
      { id: 'slow', label: 'Decel 60–90 kt / TV', check: (s) => s.speed >= 25 && s.speed <= 50 },
      { id: 'align', label: 'Pad / runway lined up', check: (s) => s.onRunwayApproach || s.agl < 40 },
      { id: 'vs', label: 'Sink < 2 m/s in flare', check: (s) => Math.abs(s.vs) < 2.5 && s.agl < 30 }
    ],
    howToFly: 'FICTIONAL. Enable TV for near-hover and extreme alpha. AB for dash. Still skill-gated on landing.',
    howToTakeoff: 'TV ON, throttle ≥70%, rotate 80 kt or lift vertically, gear up, vector to cruise.',
    howToLand: 'TV ON, gear down, slow to 60–90 kt, keep sink <2 m/s, touchdown gently.',
    specs: { empty: '12,000 lb FIC', mtow: '22,000 lb FIC', cruise: 'Mach 1.4 FIC', dash: 'Mach 2.8', tw: '~1.6–2.0', note: 'Not a real aircraft' }
  },
  {
    id: 'amphibian',
    name: 'Caravan Amphibian',
    blurb: 'Floatplane — gear state by surface is critical',
    fictional: false,
    diff: 'med',
    type: 'prop',
    color: 0xff8a32,
    accent: 0x1e66c8,
    mass: 3800,
    wingArea: 26,
    maxThrust: 4800,
    idleThrust: 100,
    drag: 0.042,
    liftCoef: 1.25,
    stallSpeed: 31,
    stallSpeedFlaps: 28,
    cruiseSpeed: 82,
    maxSpeed: 90,
    vno: 90,
    vr: 37,
    vref: 40,
    v2: 42,
    climbRate: 4.8,
    rollRate: 1.0,
    pitchRate: 0.85,
    yawRate: 0.7,
    flapLift: 0.3,
    flapDrag: 0.09,
    gearDrag: 0.03,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['0°', '20°', 'FULL'],
    flapTakeoff: 0.5,
    flapLanding: 1,
    flapApproach: 1,
    landSpeedMax: 40,
    landVertMax: 3.0,
    waterLandVertMax: 2.5,
    stallAoA: 15 * Math.PI / 180,
    stallAoAFlaps: 13 * Math.PI / 180,
    runwayOnly: false,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: true,
    ejectOk: true,
    size: 1.2,
    controls: ['THR', 'FLAPS', 'GEAR', 'COND', 'PROP', 'WATER', 'BRAKE', 'TRIM', 'REV'],
    flareStartAgl: 5.5,
    flareHoldOffFloor: 0.4,
    flareIdleThr: 0.20,
    flarePitchMin: -0.05,
    waterFlareStartAgl: 4.0,
    stableGateAgl: 152,
    approachSpeedMin: 38,
    approachSpeedMax: 45,
    tdzPreferMax: 550,
    requireSpoilersArmed: false,
    flareAssistDefault: true,
    parkCapable: true,
        windSense: 0.9,
    dutchRoll: 0.5,
    weathervane: 1.15,
    groundRollDrag: 0.032,
    takeoffAccelScale: 0.75,
    controlInertia: 0.35,
    engineSpool: 0.55,
    inputExpo: 1.38,
    tiltGain: 0.94,
    controlLag: 0.12,
    gePeak: 0.16,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    waterPitchDamp: 0.42,
    waterRolloutDrag: 0.12,
    soggyWaterRollout: true,
    nosewheelAuth: 1.05,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'GEAR', 'WATER', 'BRAKE'] },
        { id: 'SYS', controls: ['PROP', 'COND', 'REV', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      WATER: { mode: 'toggle' },
      REV: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasCondition: true,
    hasProp: true,
    hasMixture: false,
    hasSpoilers: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasWaterMode: true,
    hasReverse: true,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: false,
    takeoffChecklist: [
      { id: 'gear', label: 'Gear DOWN (land) / UP (water)', check: (s) => (s.wantWater ? !s.gearDown : s.gearDown) },
      { id: 'flaps', label: 'Flaps 20°', check: (s) => s.flaps >= 0.4 && s.flaps <= 0.6 },
      { id: 'cond', label: 'Condition / Prop FULL', check: (s) => s.conditionRun && s.propFull },
      { id: 'thr', label: 'Power UP', check: (s) => s.throttle >= 0.85 },
      { id: 'vr', label: 'Rotate ~70–75 kt', check: (s) => s.speed >= 34 && s.rotating }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear match surface!', check: (s) => (s.wantWater || s.waterMode ? !s.gearDown : s.gearDown) },
      { id: 'flaps', label: 'Flaps landing · Prop FULL', check: (s) => s.flaps >= 0.9 && s.propFull },
      { id: 'vref', label: 'Approach ~75–85 kt', check: (s) => s.speed >= 36 && s.speed <= 46 },
      { id: 'align', label: 'Aligned to surface', check: (s) => s.onRunwayApproach || s.wantWater || s.waterMode },
      { id: 'flare', label: 'Hold off / settle', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.25 && s.agl < 10) }
    ],
    howToFly: 'Amphibious Caravan. WATER toggle sets intended surface. Gear DOWN on land, gear UP on water — wrong = wreck.',
    howToTakeoff: 'Land: gear DOWN, flaps 20°, condition/prop FULL, rotate 70–75 kt. Water: gear UP critical, same flaps/power, step then fly off.',
    howToLand: 'Confirm gear for surface. Flaps landing, ~80 kt. Water: glassy technique, gear must be UP.',
    specs: { empty: '~2,533 kg', mtow: '8,750 lb', cruise: '159 KTAS', stall: '60 KCAS', climb: '~940 fpm', note: 'Wipline 8750 floats' }
  },
  {
    id: 'aerobatic',
    name: 'Extra 300',
    blurb: 'Signature 390°/s roll — sensitive pitch',
    fictional: false,
    diff: 'med',
    type: 'prop',
    color: 0xff2244,
    accent: 0xffffff,
    mass: 850,
    wingArea: 11,
    maxThrust: 3200,
    idleThrust: 60,
    drag: 0.038,
    liftCoef: 1.35,
    stallSpeed: 30,
    stallSpeedFlaps: 28,
    cruiseSpeed: 88,
    maxSpeed: 113,
    vno: 113,
    vr: 32,
    vref: 38,
    v2: 40,
    climbRate: 16.3,
    rollRate: 6.8,
    pitchRate: 2.8,
    yawRate: 1.5,
    flapLift: 0.12,
    flapDrag: 0.04,
    gearDrag: 0.02,
    flapSteps: [0, 1],
    flapLabels: ['UP', 'DN'],
    flapTakeoff: 0,
    flapLanding: 0,
    flapApproach: 0,
    landSpeedMax: 38,
    landVertMax: 3.2,
    stallAoA: 16 * Math.PI / 180,
    stallAoAFlaps: 15 * Math.PI / 180,
    gLimit: 10,
    runwayOnly: true,
    hasGear: true,
    gearFixed: true,
    gearRetractable: false,
    canWater: false,
    ejectOk: true,
    size: 0.9,
    controls: ['THR', 'MIX', 'PROP', 'FLAPS', 'BRAKE', 'TRIM', 'SMOKE'],
    flareStartAgl: 4.0,
    flareHoldOffFloor: 0.3,
    flareIdleThr: 0.15,
    flarePitchMin: -0.08,
    stableGateAgl: 100,
    approachSpeedMin: 35,
    approachSpeedMax: 42,
    tdzPreferMax: 700,
    requireSpoilersArmed: false,
    flareAssistDefault: true,
    parkCapable: true,
        windSense: 1.15,
    dutchRoll: 0.45,
    weathervane: 1.55,
    groundRollDrag: 0.012,
    takeoffAccelScale: 1.45,
    controlInertia: 0.05,
    engineSpool: 0.22,
    inputExpo: 1.05,
    tiltGain: 1.28,
    controlLag: 0.02,
    gePeak: 0.12,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    snappy: true,
    shortField: true,
    nosewheelAuth: 1.4,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['MIX', 'PROP', 'BRAKE', 'FLAPS'] },
        { id: 'SYS', controls: ['SMOKE', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      SMOKE: { mode: 'hold' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasMixture: true,
    hasProp: true,
    hasSpoilers: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: false,
    enforceFlapsLanding: false,
    enforceGear: false,
    enforceStableApproach: false,
    takeoffChecklist: [
      { id: 'mix', label: 'Mixture RICH', check: (s) => s.mixtureRich },
      { id: 'prop', label: 'Prop FULL FWD', check: (s) => s.propFull },
      { id: 'flaps', label: 'Flaps UP', check: (s) => s.flaps < 0.2 },
      { id: 'thr', label: 'Throttle FULL', check: (s) => s.throttle >= 0.9 },
      { id: 'vr', label: 'Rotate ~60–65 kt', check: (s) => s.speed >= 30 && s.rotating }
    ],
    landingChecklist: [
      { id: 'config', label: 'Prop FULL · Mix RICH', check: (s) => s.propFull && s.mixtureRich },
      { id: 'vref', label: 'Approach ~75 kt', check: (s) => s.speed >= 34 && s.speed <= 44 },
      { id: 'align', label: 'Field lined up', check: (s) => s.onRunwayApproach || s.agl < 40 },
      { id: 'flare', label: 'Idle flare · stick back', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.15 && s.agl < 8) }
    ],
    howToFly: 'Extreme roll rate (~390°/s). Light wing, sensitive elevator. Usually flaps UP. Watch VNE in dives.',
    howToTakeoff: 'MIX RICH, PROP FULL, flaps UP, full throttle, rotate 60–65 kt.',
    howToLand: 'Prop/mix full, ~75 kt final, slip if high, idle flare.',
    specs: { empty: '~680 kg', mtow: '~950 kg', cruise: '170–175 kt', vne: '220 KIAS', roll: '360–400°/s', g: '±8 to ±10' }
  },
  {
    id: 'cargo',
    name: 'C-130J Analog',
    blurb: 'Scaled Super Hercules — heavy, long rollout',
    fictional: false,
    diff: 'med',
    type: 'turboprop',
    color: 0xccaa66,
    accent: 0x334422,
    mass: 35000,
    wingArea: 120,
    maxThrust: 70000,
    idleThrust: 1200,
    drag: 0.035,
    liftCoef: 1.15,
    stallSpeed: 48,
    stallSpeedFlaps: 42,
    cruiseSpeed: 150,
    maxSpeed: 175,
    vno: 175,
    vr: 58,
    vref: 68,
    v2: 62,
    climbRate: 10,
    rollRate: 0.75,
    pitchRate: 0.55,
    yawRate: 0.4,
    flapLift: 0.45,
    flapDrag: 0.12,
    gearDrag: 0.035,
    reverseThrustFrac: 0.35,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['UP', 'TO', 'LDG'],
    flapTakeoff: 0.5,
    flapLanding: 1,
    flapApproach: 0.5,
    landSpeedMax: 70,
    landVertMax: 2.5,
    stallAoA: 14 * Math.PI / 180,
    stallAoAFlaps: 12 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    ejectOk: true,
    size: 2.4,
    controls: ['THR', 'FLAPS', 'GEAR', 'COND', 'PROP', 'REV', 'BRAKE', 'TRIM'],
    flareStartAgl: 9.0,
    flareHoldOffFloor: 0.6,
    flareIdleThr: 0.25,
    flarePitchMin: -0.04,
    stableGateAgl: 152,
    approachSpeedMin: 65,
    approachSpeedMax: 75,
    tdzPreferMax: 700,
    requireSpoilersArmed: false,
    flareAssistDefault: true,
    autobrakeCapable: true,
    parkCapable: true,
        windSense: 0.4,
    dutchRoll: 0.12,
    weathervane: 0.38,
    groundRollDrag: 0.042,
    takeoffAccelScale: 0.58,
    controlInertia: 0.72,
    engineSpool: 4.2,
    inputExpo: 1.7,
    tiltGain: 0.76,
    controlLag: 0.36,
    gePeak: 0.09,
    earlyLiftBlock: true,
    requireFlapsToRotate: true,
    longRoll: true,
    nosewheelAuth: 0.35,
    tillerHeavy: true,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'GEAR', 'BRAKE', 'REV'] },
        { id: 'SYS', controls: ['COND', 'PROP', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      REV: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasCondition: true,
    hasProp: true,
    hasSpoilers: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: true,
    hasMixture: false,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: true,
    note: 'Playable scaled C-130J analog (not full 70 t MTOW).',
    takeoffChecklist: [
      { id: 'flaps', label: 'Flaps TO', check: (s) => s.flaps >= 0.4 && s.flaps <= 0.6 },
      { id: 'cond', label: 'Condition RUN / props FULL', check: (s) => s.conditionRun && s.propFull },
      { id: 'thr', label: 'Power levers TO', check: (s) => s.throttle >= 0.85 },
      { id: 'vr', label: 'Rotate Vr → V2', check: (s) => s.speed >= 55 && s.rotating },
      { id: 'gear', label: 'Gear UP', check: (s) => s.airborne && !s.gearDown }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear DOWN · flaps LDG · props FULL', check: (s) => s.gearDown && s.flaps >= 0.9 && s.propFull },
      { id: 'stable', label: 'Stabilize ~130–145 kt', check: (s) => s.speed >= 60 && s.speed <= 78 },
      { id: 'align', label: 'Runway aligned', check: (s) => s.onRunwayApproach },
      { id: 'flare', label: 'Flare — idle', check: (s) => s.approachPhase === 'flare_window' || (s.throttle <= 0.25 && s.agl < 12) }
    ],
    howToFly: 'Large inertia, moderate roll. Long ground roll. Use condition/prop and reverse after touchdown.',
    howToTakeoff: 'Flaps TO, condition RUN, props FULL, power TO, rotate, gear up, flaps up on schedule.',
    howToLand: 'Gear down, flaps landing, props full, ~140 kt, idle/touch, ground fine/reverse/brakes.',
    specs: { empty: 'OEW ~34 t (scaled game mass)', mtow: 'up to 70 t real', cruise: '348 KTAS real', stall: '~100 kt', climb: '2,100 fpm' }
  },
  {
    id: 'glider',
    name: 'ASW 27 Glider',
    blurb: 'Energy only — spoilers for path control',
    fictional: false,
    diff: 'hard',
    type: 'glider',
    color: 0xffffff,
    accent: 0x88aacc,
    mass: 400,
    wingArea: 9.0,
    maxThrust: 0,
    idleThrust: 0,
    drag: 0.011,
    liftCoef: 1.55,
    stallSpeed: 22,
    stallSpeedFlaps: 20,
    cruiseSpeed: 28,
    maxSpeed: 73,
    vno: 55,
    vr: 25,
    vref: 28,
    v2: 30,
    climbRate: 0,
    minSink: 0.58,
    bestLD: 48,
    rollRate: 1.6,
    pitchRate: 1.2,
    yawRate: 0.8,
    flapLift: 0.25,
    flapDrag: 0.05,
    gearDrag: 0.015,
    spoilerDrag: 0.14,
    spoilerLiftKill: 0.45,
    flapSteps: [0, 0.5, 1],
    flapLabels: ['0', '−/+', 'LDG'],
    flapTakeoff: 0.5,
    flapLanding: 1,
    flapApproach: 1,
    landSpeedMax: 32,
    landVertMax: 2.0,
    stallAoA: 15 * Math.PI / 180,
    stallAoAFlaps: 14 * Math.PI / 180,
    runwayOnly: true,
    hasGear: true,
    gearFixed: false,
    gearRetractable: true,
    canWater: false,
    ejectOk: true,
    size: 1.3,
    controls: ['FLAPS', 'GEAR', 'SPOILERS', 'BALLAST', 'BRAKE', 'TRIM'],
    flareStartAgl: 4.5,
    flareHoldOffFloor: 0.3,
    flareIdleThr: 1.0,
    flarePitchMin: -0.06,
    stableGateAgl: 152,
    approachSpeedMin: 26,
    approachSpeedMax: 32,
    tdzPreferMax: 500,
    requireSpoilersArmed: false,
    flareAssistDefault: false,
    parkCapable: true,
        windSense: 1.25,
    dutchRoll: 0.65,
    weathervane: 1.6,
    groundRollDrag: 0.012,
    takeoffAccelScale: 0.0,
    controlInertia: 0.12,
    engineSpool: 0,
    inputExpo: 1.32,
    tiltGain: 1.0,
    controlLag: 0.08,
    gePeak: 0.15,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    energySpoilerPath: true,
    noToga: true,
    nosewheelAuth: 1.2,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['FLAPS', 'SPOILERS', 'GEAR', 'BRAKE'] },
        { id: 'SYS', controls: ['BALLAST', 'TRIM'] }
      ]
    },
    controlMeta: {
      FLAPS: { mode: 'step', longPress: 'stepDown' },
      SPOILERS: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasSpoilers: true,
    hasBallast: true,
    hasMixture: false,
    hasProp: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: false,
    enforceFlapsLanding: true,
    enforceGear: true,
    enforceStableApproach: true,
    takeoffChecklist: [
      { id: 'spoilers', label: 'Spoilers LOCKED CLOSED', check: (s) => !s.spoilers },
      { id: 'flaps', label: 'Flaps launch setting', check: (s) => s.flaps >= 0.3 },
      { id: 'gear', label: 'Gear DOWN', check: (s) => s.gearDown },
      { id: 'air', label: 'Airborne / energy OK', check: (s) => s.airborne && s.alt > 50 }
    ],
    landingChecklist: [
      { id: 'config', label: 'Gear DOWN · flaps landing', check: (s) => s.gearDown && s.flaps >= 0.5 },
      { id: 'spoilers', label: 'Spoilers for path', check: (s) => s.spoilers || s.agl > 80 },
      { id: 'vref', label: 'Aim ~55 kt threshold', check: (s) => s.speed >= 24 && s.speed <= 34 },
      { id: 'align', label: 'Runway aligned', check: (s) => s.onRunwayApproach },
      { id: 'flare', label: 'Round out / hold-off', check: (s) => s.approachPhase === 'flare_window' || s.agl < 8 }
    ],
    howToFly: 'No engine. Trade altitude for speed. Best L/D ~54 kt. Spoilers control glide path. Ballast raises wing loading.',
    howToTakeoff: 'Air-start from altitude (aerotow sim). Spoilers closed, flaps launch, gear down then retract after launch.',
    howToLand: 'Gear down, flaps landing, spoilers for path, ~55 kt over threshold, full spoilers after touch.',
    specs: { empty: '245 kg', max: '500 kg w/ ballast', ld: '48:1', minSink: '0.58 m/s', vne: '154 kt', wing: '9 m² AR25' }
  },
  {
    id: 'heli',
    name: 'Robinson R44',
    blurb: 'Collective hover — ETL transition, VTOL land',
    fictional: false,
    diff: 'med',
    type: 'heli',
    color: 0x336644,
    accent: 0xffcc00,
    mass: 1000,
    wingArea: 4,
    rotorArea: 80,
    maxThrust: 0,
    idleThrust: 0,
    drag: 0.055,
    liftCoef: 0.3,
    stallSpeed: 5,
    stallSpeedFlaps: 5,
    cruiseSpeed: 55,
    maxSpeed: 62,
    vno: 62,
    vr: 0,
    vref: 25,
    v2: 28,
    climbRate: 5.5,
    etlSpeed: 18,
    autoSpeed: 33,
    rollRate: 1.8,
    pitchRate: 1.5,
    yawRate: 2.2,
    flapLift: 0,
    flapDrag: 0,
    gearDrag: 0.01,
    flapSteps: [0],
    flapLabels: ['—'],
    flapTakeoff: 0,
    flapLanding: 0,
    flapApproach: 0,
    landSpeedMax: 15,
    landVertMax: 2.0,
    stallAoA: 0,
    stallAoAFlaps: 0,
    runwayOnly: false,
    hasGear: true,
    gearFixed: true,
    gearRetractable: false,
    canWater: false,
    isHeli: true,
    maxCollectiveLift: 11500,
    ejectOk: true,
    size: 1.1,
    controls: ['COLL', 'BRAKE', 'TRIM'],
    flareStartAgl: 2.5,
    flareHoldOffFloor: 0.5,
    flareIdleThr: 1.0,
    flarePitchMin: 0,
    stableGateAgl: 50,
    approachSpeedMin: 0,
    approachSpeedMax: 15,
    tdzPreferMax: 900,
    requireSpoilersArmed: false,
    flareAssistDefault: true,
    parkCapable: true,
    hoverGateAgl: 2.5,
        windSense: 0.8,
    dutchRoll: 0.0,
    weathervane: 0.7,
    groundRollDrag: 0.04,
    takeoffAccelScale: 1.0,
    controlInertia: 0.2,
    engineSpool: 1.8,
    inputExpo: 1.42,
    tiltGain: 0.84,
    controlLag: 0.2,
    gePeak: 0.2,
    earlyLiftBlock: false,
    requireFlapsToRotate: false,
    hoverSettle: true,
    vrsBite: true,
    nosewheelAuth: 0.5,
controlLayout: {
      pages: [
        { id: 'PRIMARY', controls: ['BRAKE', 'TRIM'] }
      ]
    },
    controlMeta: {
      BRAKE: { mode: 'toggle' },
      TRIM: { mode: 'jog', holdSlew: true }
    },
    hasMixture: false,
    hasProp: false,
    hasSpoilers: false,
    hasAfterburner: false,
    hasThrustVector: false,
    hasReverse: false,
    enforceFlapsLanding: false,
    enforceGear: false,
    enforceStableApproach: false,
    takeoffChecklist: [
      { id: 'rpm', label: 'RPM / governor ready', check: (s) => s.collective > 0.2 },
      { id: 'hover', label: 'Collective → hover', check: (s) => s.airborne && s.speed < 8 },
      { id: 'trans', label: 'Transition ETL ~30–40 kt', check: (s) => s.speed >= 15 },
      { id: 'climb', label: 'Climb Vy 55 kt', check: (s) => s.airborne && s.speed >= 25 }
    ],
    landingChecklist: [
      { id: 'app', label: 'Decelerate approach', check: (s) => s.speed <= 40 && s.agl < 80 },
      { id: 'hover', label: 'Hover gate ~5–8 ft', check: (s) => s.speed < 8 && s.agl < 10 },
      { id: 'align', label: 'Skids level', check: (s) => Math.abs(s.bank) < 0.25 },
      { id: 'vert', label: 'Vertical settle', check: (s) => s.speed < 5 && s.vs > -3 }
    ],
    howToFly: 'Collective controls lift. Tilt phone = cyclic. Transition through ETL (~35 kt) for efficient climb. No flaps.',
    howToTakeoff: 'Raise collective to hover, pedals (rudder) for torque, cyclic to transition, climb at 55 kt.',
    howToLand: 'Decelerate to hover ~5 ft, vertical descent, skids level, collective full down after touch.',
    specs: { empty: '~1,510 lb', mtow: '2,500 lb', cruise: '110 KIAS', vne: '120 KIAS', climb: '>1,000 fpm', hover: 'IGE charts' }
  }
];

export function getAircraft(id) {
  const base = AIRCRAFT.find((a) => a.id === id) || AIRCRAFT[0];
  const extra = HANDLING[base.id];
  return extra ? { ...base, ...extra } : base;
}

export function msToKt(ms) {
  return ms * 1.94384;
}
